#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

mkdir -p constant/triSurface

# copy DTC hull surface from resources folder
cp -f \
    "$FOAM_TUTORIALS"/resources/geometry/DTC-scaled.stl.gz \
    constant/triSurface/

./generateMesh.sh

restore0Dir

runApplication setFields

# runApplication decomposePar
runParallel -s decompose redistributePar -decompose

runParallel renumberMesh -overwrite

runParallel $(getApplication)

# runApplication reconstructPar
runParallel -s reconstruct redistributePar -reconstruct

#------------------------------------------------------------------------------
